name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**"
  pull_request:
    branches: [main]
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-14]

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build DartSassBuilder
        run: dotnet build ./DartSassBuilder --no-restore
      - name: Build DartSassBuilder.DirectoryTests
        run: dotnet build ./DartSassBuilder.DirectoryTests --no-restore
      - name: Build DartSassBuilder.ExcludeTests
        run: dotnet build ./DartSassBuilder.ExcludeTests --no-restore
      - name: Build DartSassBuilder.Tests
        run: dotnet build ./DartSassBuilder.Tests --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
